init:git hooks inject script

diff --git a/scripts/git/hooks/pre-commit b/scripts/git/hooks/pre-commit
--- a/scripts/git/hooks/pre-commit
+++ b/scripts/git/hooks/pre-commit
@@ -3,3 +3,19 @@
 printf "\e[33;1m%s\e[0m\n" 'Running the Flutter formatter'
 dart format . -l 120
 printf "\e[33;1m%s\e[0m\n" 'Finished running the Flutter formatter'
+# Run Flutter analyze and check for errors
+if ! output=$(flutter analyze); then
+    echo "COMMIT REJECTED: Flutter analyze found the following errors:"
+    echo "$output"
+    exit 1
+fi
+
+# Run Dart analyze and check for errors
+if ! output=$(dart analyze); then
+    echo "COMMIT REJECTED: Dart analyze found the following errors:"
+    echo "$output"
+    exit 1
+fi
+
+# If we made it this far, the commit is allowed
+exit 0
